AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a medical billing application's EC2 instance.

Parameters:
  ExistingVPC:
    Description: The VPC ID where the EC2 instance will be deployed.
    Type: AWS::EC2::VPC::Id

  ExistingSecurityGroup:
    Description: The ID of the existing security group for the EC2 instance.
    Type: AWS::EC2::SecurityGroup::Id

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large

#YOU WILL NEED TO MAKE CHANGES IN THE SECTION BELOW

Resources:
  MedicalBillingServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-033a1ebf088e56e81 # DO NOT CHANGE THIS
      KeyName: MedCircle-KeyPair # Specify your key pair name
      SecurityGroupIds:
        - sg-0e63f872b1eaf1e54 #Enter the Subnet Group ID here
      SubnetId: subnet-0465f3b112274dcf9 #Enter the Subnet ID here
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 20 # Size in GiB, modify as per requirement
            DeleteOnTermination: true
            VolumeType: gp2

Outputs:
  EC2InstancePublicIp:
    Description: "The public IP address of the EC2 instance"
    Value: !GetAtt MedicalBillingServer.PublicIp

  EC2InstanceId:
    Description: "The Instance ID of the EC2 instance"
    Value: !Ref MedicalBillingServer
