AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an EFS filesystem

Resources:
  MyFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: false
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      BackupPolicy:
        Status: ENABLED
      Tags:
        - Key: Name
          Value: MyEFSFileSystem

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyFileSystem
      SubnetId: subnet-0592e215833ab4f64 # Replace with your actual subnet ID
      #SecurityGroups: [sg-12345678] # Uncomment and replace with your actual security group ID if needed

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyFileSystem
      SubnetId: subnet-0aa7f7823d8404590 # Replace with your actual subnet ID
      #SecurityGroups: [sg-87654321] # Uncomment and replace with your actual security group ID if needed

Outputs:
  FileSystemId:
    Description: The ID of the EFS file system
    Value: !Ref MyFileSystem
