AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket and IAM user with access to that bucket.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: medcirclepatientdata

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: MyBucketPolicy
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MyS3Bucket}/*"

Outputs:
  S3BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
    
      Users:
        - SystemAdmin1
        - Patient1