AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group for Web Application

Parameters:
  VPCId:
    Type: String
    Description: The ID of the VPC where the security group will be created.

Resources:
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebAppSG # Optional, can be omitted
      GroupDescription: Security group for web application
      VpcId: vpc-04b9c68c5ce9b4520 #YOU MUST CHANGE THE VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allows access from any IP address
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0 # Allows access from any IP address
      SecurityGroupEgress:
        - IpProtocol: -1 # Allows all outbound traffic
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Description: The ID of the security group
    Value: !Ref WebAppSecurityGroup